name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Install npm dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display my SoftUni username
      run: echo "hris96"
  
  execute_ui_tests:
    runs-on: ubuntu-latest
    needs: build_and_unit_test
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Install npm dependencies
      run: npm install
    - name: Download Playwright browsers
      run: npx playwright install
    - name: Start app
      run: npm start &
    - name: Run UI tests
      run: npm run test:ui
  
  deploy_on_render:
    runs-on: ubuntu-latest
    needs: execute_ui_tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
